/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package edu.ijse.mvc.view;

import edu.ijse.mvc.controller.CustomerController;
import edu.ijse.mvc.controller.ItemController;
import edu.ijse.mvc.controller.OrderController;
import edu.ijse.mvc.dto.CustomerDto;
import edu.ijse.mvc.dto.ItemDto;
import edu.ijse.mvc.dto.OrderDetailDto;
import edu.ijse.mvc.dto.OrderDto;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class OrderPanel extends javax.swing.JPanel {
    
    private ItemController itemController;
    private CustomerController customerController;
    private final OrderController orderController;
    
    private ArrayList<OrderDetailDto> orderDetailDtos = new ArrayList<>();

    /**
     * Creates new form OrderPanel
     */
    public OrderPanel() {
        
        customerController = new CustomerController();
        itemController = new ItemController();
        orderController = new OrderController();
        initComponents();
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblOId = new javax.swing.JLabel();
        txtOId = new javax.swing.JTextField();
        lblCId = new javax.swing.JLabel();
        txtCId = new javax.swing.JTextField();
        lblItemCode = new javax.swing.JLabel();
        txtItemCode = new javax.swing.JTextField();
        lblQty = new javax.swing.JLabel();
        txtQty = new javax.swing.JTextField();
        lblDiscount = new javax.swing.JLabel();
        txtDiscount = new javax.swing.JTextField();
        btnCSearch = new javax.swing.JButton();
        btnISearch = new javax.swing.JButton();
        lblCustDetail = new javax.swing.JLabel();
        lblItemDetail = new javax.swing.JLabel();
        btnAddtoCart = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCart = new javax.swing.JTable();
        btnPlaceOrder = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Order Form");

        lblOId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblOId.setForeground(new java.awt.Color(204, 204, 204));
        lblOId.setText("Order Id");

        txtOId.setBackground(new java.awt.Color(204, 204, 204));

        lblCId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCId.setForeground(new java.awt.Color(204, 204, 204));
        lblCId.setText("Customer Id");

        txtCId.setBackground(new java.awt.Color(204, 204, 204));

        lblItemCode.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblItemCode.setForeground(new java.awt.Color(204, 204, 204));
        lblItemCode.setText("Item Code");

        txtItemCode.setBackground(new java.awt.Color(204, 204, 204));

        lblQty.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblQty.setForeground(new java.awt.Color(204, 204, 204));
        lblQty.setText("Qty");

        txtQty.setBackground(new java.awt.Color(204, 204, 204));

        lblDiscount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDiscount.setForeground(new java.awt.Color(204, 204, 204));
        lblDiscount.setText("Discount");

        txtDiscount.setBackground(new java.awt.Color(204, 204, 204));

        btnCSearch.setBackground(new java.awt.Color(255, 204, 0));
        btnCSearch.setForeground(new java.awt.Color(51, 51, 51));
        btnCSearch.setText("Search");
        btnCSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCSearchActionPerformed(evt);
            }
        });

        btnISearch.setBackground(new java.awt.Color(255, 204, 0));
        btnISearch.setForeground(new java.awt.Color(51, 51, 51));
        btnISearch.setText("Search");
        btnISearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnISearchActionPerformed(evt);
            }
        });

        lblCustDetail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCustDetail.setForeground(new java.awt.Color(255, 204, 0));

        lblItemDetail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblItemDetail.setForeground(new java.awt.Color(255, 204, 0));

        btnAddtoCart.setBackground(new java.awt.Color(255, 204, 0));
        btnAddtoCart.setForeground(new java.awt.Color(51, 51, 51));
        btnAddtoCart.setText("Add to Cart");
        btnAddtoCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddtoCartActionPerformed(evt);
            }
        });

        tblCart.setBackground(new java.awt.Color(51, 51, 51));
        tblCart.setForeground(new java.awt.Color(204, 204, 204));
        tblCart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblCart.setGridColor(new java.awt.Color(51, 51, 51));
        tblCart.setSelectionBackground(new java.awt.Color(255, 204, 0));
        tblCart.setSelectionForeground(new java.awt.Color(51, 51, 51));
        jScrollPane1.setViewportView(tblCart);

        btnPlaceOrder.setBackground(new java.awt.Color(255, 204, 0));
        btnPlaceOrder.setForeground(new java.awt.Color(51, 51, 51));
        btnPlaceOrder.setText("Place Order");
        btnPlaceOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaceOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(365, 365, 365)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblItemCode)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtItemCode, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCId)
                                .addGap(18, 18, 18)
                                .addComponent(txtCId, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblOId)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtOId, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblQty)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnCSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnISearch, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblCustDetail, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                    .addComponent(lblItemDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDiscount)
                                .addGap(38, 38, 38)
                                .addComponent(txtDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 189, Short.MAX_VALUE)
                                .addComponent(btnAddtoCart, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPlaceOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOId, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCId)
                        .addComponent(txtCId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCSearch))
                    .addComponent(lblCustDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblItemCode)
                            .addComponent(txtItemCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnISearch)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(lblItemDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQty)
                    .addComponent(lblDiscount)
                    .addComponent(txtDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddtoCart))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPlaceOrder)
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCSearchActionPerformed
        // TODO add your handling code here:
        searchCustomer();
        
    }//GEN-LAST:event_btnCSearchActionPerformed

    private void btnISearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnISearchActionPerformed
        // TODO add your handling code here:
        searchItem();
    }//GEN-LAST:event_btnISearchActionPerformed

    private void btnAddtoCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddtoCartActionPerformed
        // TODO add your handling code here:
        addToCart();
    }//GEN-LAST:event_btnAddtoCartActionPerformed

    private void btnPlaceOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaceOrderActionPerformed
        // TODO add your handling code here:
        placeOrder();
    }//GEN-LAST:event_btnPlaceOrderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddtoCart;
    private javax.swing.JButton btnCSearch;
    private javax.swing.JButton btnISearch;
    private javax.swing.JButton btnPlaceOrder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCId;
    private javax.swing.JLabel lblCustDetail;
    private javax.swing.JLabel lblDiscount;
    private javax.swing.JLabel lblItemCode;
    private javax.swing.JLabel lblItemDetail;
    private javax.swing.JLabel lblOId;
    private javax.swing.JLabel lblQty;
    private javax.swing.JTable tblCart;
    private javax.swing.JTextField txtCId;
    private javax.swing.JTextField txtDiscount;
    private javax.swing.JTextField txtItemCode;
    private javax.swing.JTextField txtOId;
    private javax.swing.JTextField txtQty;
    // End of variables declaration//GEN-END:variables
    
    public void searchCustomer(){
        String customerId = txtCId.getText();
        try {
            CustomerDto customerDto = customerController.searchCustomer(customerId);
            if(customerDto != null){
                lblCustDetail.setText(customerDto.getTitle()+ ". " + customerDto.getName());
            } else {
                JOptionPane.showMessageDialog(this, "Customer not found");
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    public void searchItem(){
        String itemCode = txtItemCode.getText();
        try {
            ItemDto itemDto = itemController.searchItem(itemCode);
            if(itemDto != null){
                lblItemDetail.setText(itemDto.getDescription() + " | " + itemDto.getPackSize() + " | " + itemDto.getQOH()+ " | " + itemDto.getUnitPrice());
            } else {
                JOptionPane.showMessageDialog(this, "Item not found");
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    private void loadTable() {
        String columns [] = {"Item Code", "Discount", "Qty"};
        DefaultTableModel dtm = new DefaultTableModel(columns, 0){
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tblCart.setModel(dtm);
    }
    
    private void addToCart(){
        try {
            OrderDetailDto dto = new OrderDetailDto();
            dto.setItemCode(txtItemCode.getText());
            dto.setQty(Integer.parseInt(txtQty.getText()));
            dto.setDiscount(Double.parseDouble(txtDiscount.getText()));

            orderDetailDtos.add(dto);
            Object [] rowData = {dto.getItemCode(), dto.getDiscount(), dto.getQty()};
            DefaultTableModel dtm = (DefaultTableModel) tblCart.getModel();
            dtm.addRow(rowData);
            clearItem();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    private void clearItem(){
        txtItemCode.setText("");
        txtDiscount.setText("");
        txtQty.setText("");
        lblItemDetail.setText("");
    }
    
    private void placeOrder() {
        try {
            OrderDto orderDto = new OrderDto();
            orderDto.setOrderId(txtOId.getText());
            orderDto.setCustId(txtCId.getText());
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String date = sdf.format(new Date());
            orderDto.setOrderDate(date);
            orderDto.setOrderDetailDtos(orderDetailDtos);

            String resp = orderController.placeOrder(orderDto);
            JOptionPane.showMessageDialog(this, resp);
            loadTable();
            txtCId.setText("");
            txtOId.setText("");

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e.getMessage());
        }


    }
}
